name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]  # 添加 tag 触发条件
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: https://alivault.avallon.com.cn:5101  # 默认仓库，改为私有仓库地址
  
  IMAGE_PATH: mind-map  # 完整镜像路径
  DOCKERFILE_PATH: Dockerfile  # 新增 Dockerfile 路径变量

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:       
        images: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_PATH }}  
        tags: |
          type=raw,value=latest
          type=sha

    - name: Login to Registry(aliyun)
      if: github.event_name == 'push'
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}  # 仓库登录凭证
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v3 
      with:
        context: .
        file: ${{ env.DOCKERFILE_PATH }}  # 显式指定 Dockerfile
        push: ${{ github.event_name == 'push' }}  # 仅 push 事件时推送
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        

    
